version: 2

jobs:
  build:
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: |
          docker buildx build --push \
            --build-arg CI_NAME=circleci \
            --platform linux/arm/v7,linux/arm64/v8,linux/386,linux/amd64 \
            --tag jdrouet/docker-on-ci:circleci .
